title: Psiloconvalley
description: "Exploring the intersection of consciousness, creativity, and innovation"
url: "https://psiloconvalley.github.io"
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Collections
collections:
  posts:
    output: true
    permalink: /:categories/:year/:month/:day/:title/

# Navigation
navigation:
  - title: Home
    url: /
  - title: The Mycelium
    url: /mycelium/
  - title: Declassifier   # <-- ADD THIS
    url: /declassifier/ # <-- AND THIS
  - title: Articles
    url: /articles/
  - title: About
    url: /about/

# Social
twitter: psiloconvalley
github: psiloconvalley
